# Generated by Django 5.0.14 on 2026-05-27 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('client_submission_id', models.CharField(max_length=255)),
                ('physical_table_name', models.CharField(max_length=255)),
                ('physical_row_id', models.IntegerField()),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='synced', max_length=50)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form')),
                ('form_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.formversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collect_submission_index',
                'ordering': ['-created_at'],
                'unique_together': {('device_id', 'client_submission_id', 'form')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_id', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/media/')),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('voice', 'Voice'), ('signature', 'Signature'), ('file', 'File')], max_length=50)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='submissions.submissionindex')),
            ],
            options={
                'db_table': 'collect_submission_media',
                'ordering': ['-created_at'],
            },
        ),
    ]
