# Generated by Django 5.0.14 on 2026-05-27 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('form_first', 'Form First'), ('map_first', 'Map First')], default='form_first', max_length=50)),
                ('geometry_type', models.CharField(choices=[('none', 'None'), ('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon'), ('mixed', 'Mixed')], default='none', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('submission_table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='projects.project')),
            ],
            options={
                'db_table': 'collect_form',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('version_label', models.CharField(max_length=100)),
                ('schema', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('is_published', models.BooleanField(default=False)),
                ('physical_table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_form_versions', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='forms.form')),
            ],
            options={
                'db_table': 'collect_form_version',
                'ordering': ['-version_number'],
                'unique_together': {('form', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='form',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_forms', to='forms.formversion'),
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('project', 'slug')},
        ),
    ]
