# Generated by Django 5.0.14 on 2026-05-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The internal JSON type identifier (e.g. 'text', 'polygon')", max_length=50, unique=True)),
                ('label', models.CharField(help_text="Human-readable label for the UI (e.g. 'Single-line text input')", max_length=100)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the field's purpose")),
                ('category', models.CharField(help_text="Category for grouping in the UI (e.g. 'Basic', 'GIS', 'Media')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this field type is currently available for form building')),
            ],
            options={
                'verbose_name': 'Form Field Type',
                'verbose_name_plural': 'Form Field Types',
                'db_table': 'forms_field_type',
                'ordering': ['category', 'name'],
            },
        ),
    ]
