# Generated by Django 5.0.14 on 2026-05-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formfieldtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldtype',
            name='properties_schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON schema dictating what configuration properties are allowed for this field'),
        ),
    ]
