"""
Django settings for zingsa_collect project.

Generated by 'django-admin startproject' using Django 5.0.14.
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-m-m95xk59(-wt)#v63ok)rf+^+&x2r0i$*smg)6+alk=vjkv^z')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1')

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,172.30.5.24,*').split(',')

# Windows-specific GDAL/GEOS configuration (bypassed when running in Docker)
if os.name == 'nt' and not os.environ.get('IN_DOCKER'):
    GDAL_LIBRARY_PATH = r"C:\Program Files\PostgreSQL\16\bin\libgdal-34.dll"
    GEOS_LIBRARY_PATH = r"C:\Program Files\PostgreSQL\16\bin\libgeos_c.dll"

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # GeoDjango spatial framework

    # Third-party packages
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'djoser',
    'django_filters',
    'drf_spectacular',
    'django_celery_beat',
    'channels',
    'auditlog',
    'simple_history',
    'storages',

    # ZINGSA Collect starter applications
    'apps.accounts',
    'apps.organizations',
    'apps.projects',
    'apps.forms',
    'apps.submissions',
    'apps.mediafiles',
    'apps.sync',
    'apps.geospatial',
    'apps.analytics',
    'apps.audittrail',
    'apps.feedback',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Put CorsMiddleware as high as possible
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('DJANGO_DB_NAME', 'zingsa_collect'),
        'USER': os.environ.get('DJANGO_DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DJANGO_DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DJANGO_DB_PORT', '8200'),
    }
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = os.environ.get('TIME_ZONE', 'Africa/Harare')
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images) and Media files
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Next.js static export served alongside the API (pnpm build:ux → ../ux_ui/)
# BASE_DIR is config/; project root is one level up.
UX_UI_ROOT = BASE_DIR.parent / 'ux_ui'
_ux_ui_flag = os.environ.get('UX_UI_ENABLED', '').strip().lower()
if _ux_ui_flag in ('true', '1', 'yes'):
    UX_UI_ENABLED = True
elif _ux_ui_flag in ('false', '0', 'no'):
    UX_UI_ENABLED = False
else:
    UX_UI_ENABLED = (UX_UI_ROOT / 'index.html').is_file()

# Storage Configuration (S3 / MinIO via django-storages)
USE_S3 = os.environ.get('USE_S3', 'False').lower() in ('true', '1')

if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN') or None
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_QUERYSTRING_AUTH = False          # public bucket — no signed URLs
    AWS_S3_URL_PROTOCOL = 'http:'        # MinIO is HTTP in local/dev

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Headers
CORS_ALLOW_ALL_ORIGINS = True

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'common.exception_handler.collect_exception_handler',
    # Keep ?format= for our export APIs (xlsx/csv/...). DRF's default uses
    # this query param for content negotiation and returns 404 for unknown formats.
    'URL_FORMAT_OVERRIDE': None,
}

# SimpleJWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_OBTAIN_SERIALIZER': 'apps.accounts.serializers.token_serializers.CustomTokenObtainPairSerializer',
}

# Djoser Authentication Settings
DJOSER = {
    'LOGIN_FIELD': 'username',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'SERIALIZERS': {
        'user_create': 'apps.accounts.serializers.user_serializers.CollectUserCreateSerializer',
        'user': 'apps.accounts.serializers.user_serializers.CollectUserSerializer',
        'current_user': 'apps.accounts.serializers.user_serializers.CollectUserSerializer',
    },
}

# Channels Channel Layer (Redis)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.environ.get('REDIS_URL', 'redis://127.0.0.1:8201/0')],
        },
    },
}

# Celery Configurations
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:8201/1')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:8201/2')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    "sweep-uncompressed-images": {
        "task": "apps.mediafiles.tasks.sweep_uncompressed_images",
        "schedule": crontab(minute=0, hour="*/6"),  # Every 6 hours
    },
}

# drf-spectacular Settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'ZINGSA Collect API',
    'DESCRIPTION': 'Backend API for ZINGSA Collect dynamic data collection application',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Static files directories
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# ─────────────────────────────────────────────────────────
# Jazzmin Admin Theming — BUIMS Portal style
# ─────────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    # Browser tab / window title
    "site_title": "ZINGSA Collect",

    # Login screen header
    "site_header": "ZINGSA Collect",

    # Brand text (top-left in sidebar, max ~19 chars)
    "site_brand": "ZINGSA Collect",

    # Copyright in footer
    "copyright": "ZINGSA Collect © 2026. All rights reserved.",

    # Welcome text on login page
    "welcome_sign": "Welcome to ZINGSA Collect",

    # ── Sidebar navigation icons (FontAwesome 5 free) ──
    "icons": {
        "accounts.User": "fas fa-users-cog",
        "auth.Group": "fas fa-shield-alt",
        "organizations.Organization": "fas fa-building",
        "projects.Project": "fas fa-project-diagram",
        "forms.Form": "fas fa-file-alt",
        "forms.FormVersion": "fas fa-code-branch",
        "forms.FormFieldType": "fas fa-list-alt",
        "submissions.Submission": "fas fa-paper-plane",
        "mediafiles.MediaFile": "fas fa-photo-video",
        "analytics.AnalyticsEvent": "fas fa-chart-bar",
        "audittrail.AuditEntry": "fas fa-clipboard-list",
        "auditlog.LogEntry": "fas fa-history",
        "django_celery_beat.PeriodicTask": "fas fa-clock",
        "django_celery_beat.ClockedSchedule": "fas fa-stopwatch",
        "django_celery_beat.CrontabSchedule": "fas fa-calendar-alt",
        "django_celery_beat.IntervalSchedule": "fas fa-hourglass-half",
        "django_celery_beat.SolarSchedule": "fas fa-sun",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # ── Top-bar links ──
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],

    # ── Sidebar behaviour ──
    "show_sidebar": True,
    "navigation_expanded": True,

    # ── Custom CSS / JS ──
    "custom_css": "css/admin_custom.css",
    "custom_js": None,

    # ── Ordering: group models in sidebar by app ──
    "order_with_respect_to": [
        "accounts",
        "organizations",
        "projects",
        "forms",
        "submissions",
        "mediafiles",
        "analytics",
        "audittrail",
        "auth",
        "django_celery_beat",
    ],

    # Hide these models from the sidebar
    "hide_models": [],

    # Custom dashboard template
    "custom_links": {},

    # Change list display style
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    # ── Dark navy sidebar (matches BUIMS) ──
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
